#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          0 #12
bspc config top_padding		35px

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a Nautilus state=floating

xset -dpms s off # turn of screensaver

polybar example &
