#! /bin/sh

sxhkd &

if  xrandr | grep "HDMI-1-1 connected"; then
	xrandr --output HDMI-1-1 --primary --mode 2560x1440 --rotate normal --output eDP-1-1 --mode 1920x1080 --rotate normal --right-of HDMI-1-1
	bspc monitor HDMI-1-1 -d 1 2 3 4 5 6
	bspc monitor eDP-1-1 -d 7 8 9 0
elif xrandr | grep "HDMI-1 connected"; then
	xrandr --output HDMI-1 --primary --mode 2560x1440 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1
	bspc monitor HDMI-1 -d 1 2 3 4 5 6
	bspc monitor eDP-1 -d 7 8 9 0
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width        0
bspc config window_gap          0 #12
bspc config top_padding		35px

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus	 true

# find name using `xprop | grep WM_CLASS`
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Pcmanfm state=floating
#bspc rule -a blankscreen state=tiled

xset -dpms s off # turn of screensaver

polybar large &
polybar small &
feh --bg-fill --randomize ~/Pictures/Wallpapers/*
